profile:
  MacPro:
    on: 30
    off: 90
  MacStudio:
    on: 90
    off: 30
  MacMini:
    on: 100
    off: 120
port:
  0:
    profile: MacPro
    offset: 0
  1:
    profile: MacStudio
    offset: 0
